### ISSUE TITLE
How to deal with the asynchronous service

### ISSUE THREAD

**Issue by zhangpp520** [mariocasciaro/scatter#30]
Scatter can make the service become a dependency is so powerful,but if an injected service is an asynchronous method and need an callback argument,how deal with that?

**Comment by mariocasciaro** [comment]
You can just return a promise from your service. You can use any Promises/A+ implementation like https://github.com/petkaantonov/bluebird or https://github.com/cujojs/when

**Comment by zhangpp520** [comment]
Thank you so much.I think maybe you can mention that in the doc.
