### ISSUE TITLE
How can I find the uncaught exceptions  when loading particle?

### ISSUE THREAD

**Issue by zhangpp520** [mariocasciaro/scatter#32]
Sometimes,I make mistakes,something like forget to install modules.So,When I start the app,it just hangs there.
If I don't use Scatter,I will see the error stacks in the console.

Why dosen't Scatter just throw the exceptions?or Can I see the errors in the console?

**Comment by mariocasciaro** [comment]
Try to provide a `log` function to the Scatter constructor, this will give you a fine grained logging of what's happening in the Scatter internals.
Scatter uses promises, so you can  `catch` any exception and log it:

```
scatter.load('your_initial_component')
.then(function(say) {
  say.doSay();
})
.catch(function(err) {
  console.log(err)
})
```

**Comment by zhangpp520** [comment]
Thanks!
